server:
  port: 1112
  servlet:
    contextPath: /api/school

spring:
  datasource:
    url: jdbc:postgresql://localhost:2324/schooldb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5670
    username: guest
    password: guest

  cloud:
    stream:
      function:
        definition: schoolReceiver
      bindings:
        schoolReceiver-in-0:
          destination: schoolQueue
          group: my-group
          content-type: application/json
      rabbit:
        bindings:
          schoolReceiver-in-0:
            consumer:
              auto-bind-dlq: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enable: true